title: Traffic Forecasting Project
# logo: /assets/img/display_image_circle.png
# description: text below image
description: This repository explores multiple datasets to analyze road traffic and models for traffic forecasting.
# show_downloads: true
theme: jekyll-theme-tactile